version: "3.2"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pg-database
    ports:
      - '5432:5432'
  web: 
    build: ./api
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pg-database
      POSTGRES_HOST: db
    volumes:
      - ./API/src:/usr/app/src
  db_seeder:
    image: andywer/plow
    depends_on:
      - postgres
    env_file: ./.env
    environment:
      PGHOST: db
    restart: "no"
    volumes:
      - ./API/migrations:/migrations
      - ./API/seeds:/seeds